import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { HeroHighlight} from '../components/ui/Hero-Bg'
import { ThemeProvider } from "./theme-provider";
import { dark } from '@clerk/themes';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
      elements: {
        formButtonPrimary:
            'bg-black text-white hover:text-slate-800',
      }
    }}
    >
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-[#121212] bg-opacity-100`} >
        
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

          {children}

        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
